sudo: true

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then bash -x ci_scripts/linux_gcc_setup.sh; export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "clang++" ]; then bash -x ci_scripts/linux_clang_setup.sh; export CXX="clang++-3.7" CC="clang-3.7"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "g++" ]; then bash -x ci_scripts/osx_gcc_setup.sh; export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" = "clang++" ]; then bash -x ci_scripts/osx_clang_setup.sh; fi  

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - make test
  
notifications:
  email:
    recipients: adastley@gmail.com
    on_success: change
    on_failure: change
