language: cpp

compiler:
  - gcc

# need to install the Boost libraries to the sandbox
before_script:
  - yes | sudo add-apt-repository ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.55-context-dev

script: 
  - mkdir build
  - cd build
  - cmake ../project_files
  - make
  
notifications:
  email:
    recipients: adastley@gmail.com
    on_success: change
    on_failure: change
