language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ./build_scripts/linux_setup.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo ./build_scripts/osx_setup.sh; fi 

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - make test
  
notifications:
  email:
    recipients: adastley@gmail.com
    on_success: change
    on_failure: change
