language: cpp

compiler:
  - gcc
  
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - p7zip-full

before_script:
  - openssl version -a
  # Install latest boost
  - curl https://files.adrianastley.com/programming/boost_1_58_0.7z > boost_1_58_0.7z
  - 7z x boost_1_58_0.7z
  - cd boost_1_58_0
  - ./bootstrap.sh --with-libraries=context
  - sudo ./b2 install > /dev/null
  # Get back to the root
  - cd ../

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - make test
  
notifications:
  email:
    recipients: adastley@gmail.com
    on_success: change
    on_failure: change
